[project]
name = "luolamies"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "lxml>=6.1.3",
    "mwparserfromhell>=0.7.2",
    "pyarrow>=25.0.1",
    "torch>=2.14.0",
    "poletti",
    "numpy>=2.5.3",
    "skypilot>=0.13.0",
]

[tool.uv.sources]
poletti = { path = "poletti" }


[tool.pyrefly]
